name: zhijian
version: '1.1.0-SNAPSHOT'
main: org.fgg2333.zhijian.Zhijian
api-version: '1.21'
description: 指尖Server Plugin

commands:
  zhijian:
    description: Zhijian command
    usage: /<command> about
    permission: zhijian.wanjia
  tpa:
    description: 申请传送
    usage: /tpa <player>
    permission: zhijian.wanjia
  tpaccept:
    description: 同意传送
    usage: /tpaccept
    permission: zhijian.wanjia
  tpano:
    description: 拒绝传送
    usage: /tpano
    permission: zhijian.wanjia

    permissions:
      zhijian.wanjia:
        description: 玩家基础
        default: false
      zhijian.guanli:
        description: 管理员身份校验
        default: false