name: zhijian
version: '1.2.0-SNAPSHOT'
main: org.fgg2333.zhijian.Zhijian
api-version: '1.21'
description: 指尖Server Plugin

commands:
  zhijian:
    description: Zhijian command
    usage: /<command> about
    permission: zhijian.wanjia
  tpa:
    description: 申请传送
    usage: /tpa <player>
    permission: zhijian.wanjia
  tpaccept:
    description: 同意传送
    usage: /tpaccept
    permission: zhijian.wanjia
  tpano:
    description: 拒绝传送
    usage: /tpano
    permission: zhijian.wanjia
  back:
    description: 返回到上次的位置
    usage: /back
    permission: zhijian.wanjia
  res:
    description: Add, teleport to, get info about, delete, or list saved locations
    usage: /res <add|tp|about|del|list> <name>
    permission: zhijian.wanjia

    permissions:
      zhijian.wanjia:
        description: 玩家基础
        default: false
      zhijian.guanli:
        description: 管理员身份校验
        default: false